"""add_profile_complete_to_farmers

Revision ID: 4351f7d11d0d
Revises: d361ef5ced71
Create Date: 2026-09-02 23:09:50.152752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4351f7d11d0d'
down_revision: Union[str, Sequence[str], None] = 'd361ef5ced71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('profile_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'profile_complete')
    # ### end Alembic commands ###
