"""add callback_session_id to sms_sessions

Revision ID: 44a590b005b1
Revises: c4f1f5a2b8d9
Create Date: 2026-07-28 10:03:51.295071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a590b005b1'
down_revision: Union[str, Sequence[str], None] = 'c4f1f5a2b8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('counties', sa.Column('longitude', sa.Float(), nullable=True))
    op.execute('UPDATE counties SET latitude = 0.0 WHERE latitude IS NULL')
    op.execute('UPDATE counties SET longitude = 0.0 WHERE longitude IS NULL')
    op.alter_column('counties', 'latitude', nullable=False)
    op.alter_column('counties', 'longitude', nullable=False)
    op.create_unique_constraint('uq_farmer_crop', 'farmer_crops', ['farmer_id', 'crop_id'])
    op.create_unique_constraint('uq_farmer_livestock', 'farmer_livestock', ['farmer_id', 'livestock_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_farmer_livestock', 'farmer_livestock', type_='unique')
    op.drop_constraint('uq_farmer_crop', 'farmer_crops', type_='unique')
    op.drop_column('counties', 'longitude')
    op.drop_column('counties', 'latitude')
    # ### end Alembic commands ###
