"""Initial database schema

Revision ID: 9ea603b718c4
Revises: 
Create Date: 2026-07-02 13:56:40.791713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea603b718c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultural_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('FERTILIZER', 'PESTICIDE', 'HERBICIDE', 'FUNGICIDE', 'SEED', 'ANIMAL_FEED', 'VETERINARY', name='productcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultural_products_category'), 'agricultural_products', ['category'], unique=False)
    op.create_index(op.f('ix_agricultural_products_product_name'), 'agricultural_products', ['product_name'], unique=False)
    op.create_table('counties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counties_name'), 'counties', ['name'], unique=True)
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=True)
    op.create_table('livestock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_name'), 'livestock', ['name'], unique=True)
    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('CROP', 'LIVESTOCK', 'GENERAL', name='advisorycategory'), nullable=False),
    sa.Column('county_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_category'), 'advisories', ['category'], unique=False)
    op.create_index(op.f('ix_advisories_county_id'), 'advisories', ['county_id'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('expert_type', sa.Enum('AGRICULTURE', 'VETERINARY', name='experttype'), nullable=False),
    sa.Column('county_id', sa.UUID(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_county_id'), 'experts', ['county_id'], unique=False)
    op.create_index(op.f('ix_experts_expert_type'), 'experts', ['expert_type'], unique=False)
    op.create_index(op.f('ix_experts_phone_number'), 'experts', ['phone_number'], unique=True)
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('county_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_county_id'), 'farmers', ['county_id'], unique=False)
    op.create_index(op.f('ix_farmers_national_id'), 'farmers', ['national_id'], unique=True)
    op.create_index(op.f('ix_farmers_phone_number'), 'farmers', ['phone_number'], unique=True)
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('county_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('market_name', sa.String(length=150), nullable=False),
    sa.Column('minimum_price', sa.Float(), nullable=False),
    sa.Column('maximum_price', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_county_id'), 'market_prices', ['county_id'], unique=False)
    op.create_index(op.f('ix_market_prices_crop_id'), 'market_prices', ['crop_id'], unique=False)
    op.create_index(op.f('ix_market_prices_market_name'), 'market_prices', ['market_name'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    op.create_table('expert_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_requests_expert_id'), 'expert_requests', ['expert_id'], unique=False)
    op.create_index(op.f('ix_expert_requests_farmer_id'), 'expert_requests', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_expert_requests_status'), 'expert_requests', ['status'], unique=False)
    op.create_table('farmer_crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('farm_size', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_crops_crop_id'), 'farmer_crops', ['crop_id'], unique=False)
    op.create_index(op.f('ix_farmer_crops_farmer_id'), 'farmer_crops', ['farmer_id'], unique=False)
    op.create_table('farmer_livestock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('livestock_id', sa.UUID(), nullable=False),
    sa.Column('herd_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_livestock_farmer_id'), 'farmer_livestock', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_livestock_livestock_id'), 'farmer_livestock', ['livestock_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('WEATHER', 'MARKET_PRICE', 'DISEASE_ALERT', 'RECOMMENDATION', 'EXPERT_UPDATE', 'SUBSCRIPTION', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_farmer_id'), 'notifications', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('CROP', 'LIVESTOCK', name='recommendationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_farmer_id'), 'recommendations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_table('sms_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('CROP_RECOMMENDATION', 'LIVESTOCK_RECOMMENDATION', 'EXPERT_REQUEST', name='sessiontype'), nullable=False),
    sa.Column('session_status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_sessions_farmer_id'), 'sms_sessions', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_sms_sessions_session_status'), 'sms_sessions', ['session_status'], unique=False)
    op.create_index(op.f('ix_sms_sessions_session_type'), 'sms_sessions', ['session_type'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_farmer_id'), 'subscriptions', ['farmer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_farmer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sms_sessions_session_type'), table_name='sms_sessions')
    op.drop_index(op.f('ix_sms_sessions_session_status'), table_name='sms_sessions')
    op.drop_index(op.f('ix_sms_sessions_farmer_id'), table_name='sms_sessions')
    op.drop_table('sms_sessions')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_farmer_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_farmer_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_farmer_livestock_livestock_id'), table_name='farmer_livestock')
    op.drop_index(op.f('ix_farmer_livestock_farmer_id'), table_name='farmer_livestock')
    op.drop_table('farmer_livestock')
    op.drop_index(op.f('ix_farmer_crops_farmer_id'), table_name='farmer_crops')
    op.drop_index(op.f('ix_farmer_crops_crop_id'), table_name='farmer_crops')
    op.drop_table('farmer_crops')
    op.drop_index(op.f('ix_expert_requests_status'), table_name='expert_requests')
    op.drop_index(op.f('ix_expert_requests_farmer_id'), table_name='expert_requests')
    op.drop_index(op.f('ix_expert_requests_expert_id'), table_name='expert_requests')
    op.drop_table('expert_requests')
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_market_name'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_county_id'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_farmers_phone_number'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_national_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_county_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_experts_phone_number'), table_name='experts')
    op.drop_index(op.f('ix_experts_expert_type'), table_name='experts')
    op.drop_index(op.f('ix_experts_county_id'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_advisories_county_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_category'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_livestock_name'), table_name='livestock')
    op.drop_table('livestock')
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_counties_name'), table_name='counties')
    op.drop_table('counties')
    op.drop_index(op.f('ix_agricultural_products_product_name'), table_name='agricultural_products')
    op.drop_index(op.f('ix_agricultural_products_category'), table_name='agricultural_products')
    op.drop_table('agricultural_products')
    # ### end Alembic commands ###
