"""full_sms_ussd_redesign

Revision ID: d361ef5ced71
Revises: 44a590b005b1
Create Date: 2026-07-29 09:30:15.317601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd361ef5ced71'
down_revision: Union[str, Sequence[str], None] = '44a590b005b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_sessions', sa.Column('last_message_id', sa.String(length=120), nullable=True))
    op.add_column('sms_sessions', sa.Column('invalid_reply_count', sa.Integer(), nullable=True))
    op.execute('UPDATE sms_sessions SET invalid_reply_count = 0 WHERE invalid_reply_count IS NULL')
    op.alter_column('sms_sessions', 'invalid_reply_count', nullable=False)
    op.execute("UPDATE sms_sessions SET current_step = '0' WHERE current_step !~ '^[0-9]+$'")
    op.alter_column('sms_sessions', 'current_step',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='current_step::integer')
    op.create_index(op.f('ix_sms_sessions_last_message_id'), 'sms_sessions', ['last_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_sessions_last_message_id'), table_name='sms_sessions')
    op.alter_column('sms_sessions', 'current_step',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('sms_sessions', 'invalid_reply_count')
    op.drop_column('sms_sessions', 'last_message_id')
    # ### end Alembic commands ###
